Repository catalyst-cooperative/pudl, pull requests merged in 2023-11, with the labels that each got.

#2936 Add data maturity for 923m
  docs/release_notes.rst
  migrations/versions/1ceb9897fd34_add_data_maturity_to_eia923m_tables.py
  src/pudl/analysis/allocate_gen_fuel.py
  src/pudl/extract/eia923.py
  src/pudl/extract/excel.py
  src/pudl/metadata/resources/eia.py
  src/pudl/metadata/resources/eia923.py
  src/pudl/metadata/sources.py
  src/pudl/output/eia.py
  src/pudl/output/eia923.py
  src/pudl/package_data/eia923/column_maps/boiler_fuel.csv
  src/pudl/package_data/eia923/column_maps/emissions_control.csv
  src/pudl/package_data/eia923/column_maps/fuel_receipts_costs.csv
  src/pudl/package_data/eia923/column_maps/generation_fuel.csv
  src/pudl/package_data/eia923/column_maps/generator.csv
  src/pudl/package_data/eia923/column_maps/plant_frame.csv
  src/pudl/package_data/eia923/column_maps/stocks.csv
  src/pudl/package_data/eia923/file_map.csv
  src/pudl/package_data/eia923/page_map.csv
  src/pudl/package_data/eia923/skipfooter.csv
  src/pudl/package_data/eia923/skiprows.csv
  src/pudl/package_data/settings/etl_fast.yml
  src/pudl/package_data/settings/etl_full.yml
  src/pudl/settings.py
  src/pudl/transform/eia923.py
  src/pudl/validate.py
  test/unit/settings_test.py
  test/validate/eia_test.py
  test/validate/mcoe_test.py
Labels: eia923, rmi

#3004 Update sources, DOI and copyright link in PUDL
  src/pudl/metadata/classes.py
  src/pudl/metadata/constants.py
  src/pudl/metadata/sources.py
  src/pudl/workspace/datastore.py
Labels: datapkg, zenodo

#2968 Set up reproducible Python environments with conda-lock
  .github/workflows/bot-auto-merge.yml
  .github/workflows/build-deploy-pudl.yml
  .github/workflows/pytest.yml
  .github/workflows/update-conda-lockfile.yml
  .github/workflows/update-lockfile.yml
  .github/workflows/zenodo-cache-sync.yml
  .gitignore
  .readthedocs.yaml
  MANIFEST.in
  Makefile
  README.rst
  devtools/.gitignore
  devtools/environment.yml
  docker-compose.yml
  docker/.env
  docker/Dockerfile
  docker/docker-compose.yml
  docker/gcp_pudl_etl.sh
  docs/conf.py
  docs/dev/annual_updates.rst
  docs/dev/build_docs.rst
  docs/dev/clone_ferc1.rst
  docs/dev/dev_dagster.rst
  docs/dev/dev_setup.rst
  docs/dev/nightly_data_builds.rst
  docs/dev/project_management.rst
  docs/dev/pudl_id_mapping.rst
  docs/dev/run_the_etl.rst
  docs/dev/testing.rst
  docs/docs-environment.yml
  docs/release_notes.rst
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  pyproject.toml
  src/pudl/etl/glue_assets.py
  src/pudl/ferc_to_sqlite/cli.py
  src/pudl/output/ferc714.py
  test/test-environment.yml
  tox.ini
Labels: dependencies

#3040 Add EIA860 2022 final release data
  docs/release_notes.rst
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  src/pudl/package_data/eia860/file_map.csv
  src/pudl/package_data/eia860/skiprows.csv
  src/pudl/package_data/glue/pudl_id_mapping.xlsx
  src/pudl/package_data/glue/utility_id_pudl.csv
  src/pudl/workspace/datastore.py
  test/validate/eia_test.py
  test/validate/mcoe_test.py
Labels: eia860, rmi

#3048 Eia861 2022 final release
  docs/release_notes.rst
  src/pudl/package_data/eia861/column_maps/advanced_metering_infrastructure_eia861.csv
  src/pudl/package_data/eia861/column_maps/balancing_authority_eia861.csv
  src/pudl/package_data/eia861/column_maps/delivery_companies_eia861.csv
  src/pudl/package_data/eia861/column_maps/demand_response_eia861.csv
  src/pudl/package_data/eia861/column_maps/distribution_systems_eia861.csv
  src/pudl/package_data/eia861/column_maps/dynamic_pricing_eia861.csv
  src/pudl/package_data/eia861/column_maps/energy_efficiency_eia861.csv
  src/pudl/package_data/eia861/column_maps/frame_eia861.csv
  src/pudl/package_data/eia861/column_maps/mergers_eia861.csv
  src/pudl/package_data/eia861/column_maps/net_metering_eia861.csv
  src/pudl/package_data/eia861/column_maps/non_net_metering_eia861.csv
  src/pudl/package_data/eia861/column_maps/operational_data_eia861.csv
  src/pudl/package_data/eia861/column_maps/reliability_eia861.csv
  src/pudl/package_data/eia861/column_maps/sales_eia861.csv
  src/pudl/package_data/eia861/column_maps/service_territory_eia861.csv
  src/pudl/package_data/eia861/column_maps/short_form_eia861.csv
  src/pudl/package_data/eia861/column_maps/utility_data_eia861.csv
  src/pudl/package_data/eia861/file_map.csv
  src/pudl/package_data/eia861/skiprows.csv
  src/pudl/workspace/datastore.py
Labels: new-data, eia861, rmi

#3056 Always take lockfile version from current branch when merging
  .gitattributes
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
Labels: dependencies

#2267 Update PUDL to SQLAlchemy 2.0
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  pyproject.toml
  src/pudl/analysis/allocate_gen_fuel.py
  src/pudl/analysis/state_demand.py
  src/pudl/io_managers.py
  src/pudl/output/epacems.py
  test/unit/io_managers_test.py
Labels: dependencies, inframundo

#3060 Use ruff instead of black for autoformatting
  .pre-commit-config.yaml
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  pyproject.toml
  src/pudl/analysis/allocate_gen_fuel.py
  src/pudl/analysis/classify_plants_ferc1.py
  src/pudl/analysis/ferc1_eia_record_linkage.py
  src/pudl/analysis/ferc1_eia_train.py
  src/pudl/analysis/plant_parts_eia.py
  src/pudl/helpers.py
  src/pudl/metadata/fields.py
  src/pudl/output/eia.py
  src/pudl/transform/classes.py
  src/pudl/transform/eia860.py
  src/pudl/transform/eia861.py
  src/pudl/transform/eia923.py
  src/pudl/transform/ferc1.py
  test/unit/transform/classes_test.py
Labels: dependencies

#3074 Update development setup documentation
  docs/conf.py
  docs/dev/dev_setup.rst
Labels: docs

#3080 Simplify process of bootstrapping pudl-dev conda env.
  .github/workflows/update-conda-lockfile.yml
  Makefile
  docs/dev/dev_setup.rst
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
Labels: dependencies

#3084 Make nightly build outputs smaller
  devtools/sqlite_to_duckdb.py
  docker/docker-compose.yml
  docker/gcp_pudl_etl.sh
  docker/local_pudl_etl.sh
  docs/data_access.rst
  src/pudl/metadata/constants.py
Labels: output, cloud, nightly-builds

#3051 Refactor PUDL to use Pydantic v2
  .github/workflows/pytest.yml
  .gitignore
  Makefile
  devtools/materialize_asset.py
  docs/conf.py
  docs/release_notes.rst
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  pyproject.toml
  src/pudl/__init__.py
  src/pudl/analysis/timeseries_cleaning.py
  src/pudl/cli/etl.py
  src/pudl/etl/__init__.py
  src/pudl/etl/analysis_assets.py
  src/pudl/extract/eia_bulk_elec.py
  src/pudl/extract/excel.py
  src/pudl/ferc_to_sqlite/__init__.py
  src/pudl/ferc_to_sqlite/cli.py
  src/pudl/glue/ferc1_eia.py
  src/pudl/helpers.py
  src/pudl/io_managers.py
  src/pudl/metadata/classes.py
  src/pudl/metadata/helpers.py
  src/pudl/metadata/resources/eia860.py
  src/pudl/metadata/resources/eia923.py
  src/pudl/metadata/resources/ferc1_eia_record_linkage.py
  src/pudl/metadata/resources/glue.py
  src/pudl/output/ferc1.py
  src/pudl/output/pudltabl.py
  src/pudl/settings.py
  src/pudl/transform/classes.py
  src/pudl/transform/ferc1.py
  src/pudl/workspace/datastore.py
  src/pudl/workspace/setup.py
  test/conftest.py
  test/integration/console_scripts_test.py
  test/integration/etl_test.py
  test/integration/ferc_dbf_extract_test.py
  test/integration/glue_test.py
  test/unit/io_managers_test.py
  test/unit/settings_test.py
  test/unit/transform/classes_test.py
Labels: dependencies

#3073 Eia923 2022 final release q4 update Nov 21
  .github/workflows/zenodo-cache-sync.yml
  README.rst
  docs/release_notes.rst
  docs/templates/eia923_child.rst.jinja
  src/pudl/package_data/eia923/file_map.csv
  src/pudl/package_data/eia923/skiprows.csv
  src/pudl/workspace/datastore.py
  test/validate/eia_test.py
  test/validate/mcoe_test.py
Labels: eia923, new-data, rmi
