Repository catalyst-cooperative/pudl, pull requests merged in 2023-12, with the labels that each got.

#3094 Rename dbf-derived FERC SQLite DBs
  devtools/datasette/publish.py
  docs/data_access.rst
  docs/dev/clone_ferc1.rst
  docs/dev/run_the_etl.rst
  docs/intro.rst
  docs/release_notes.rst
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  pyproject.toml
  src/pudl/convert/censusdp1tract_to_sqlite.py
  src/pudl/extract/ferc1.py
  src/pudl/extract/ferc2.py
  src/pudl/extract/ferc6.py
  src/pudl/extract/ferc60.py
  src/pudl/glue/ferc1_eia.py
  src/pudl/io_managers.py
  src/pudl/metadata/classes.py
  src/pudl/metadata/fields.py
  src/pudl/metadata/templates/datasette-metadata.yml.jinja
  src/pudl/workspace/setup_cli.py
  test/integration/datasette_metadata_test.py
Labels: ferc1, output, sqlite, ferc2, dbf, ferc6, ferc60

#2895 Add support for choosing between multiprocess and inprocess executors via cli flag
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  src/pudl/cli/etl.py
  src/pudl/ferc_to_sqlite/cli.py
  src/pudl/helpers.py
Labels: community

#2964 Improve flexibility for publishing options
  .github/workflows/build-deploy-pudl.yml
  docker/gcp_pudl_etl.sh
Labels: community

#3124 Add GHA workflow for release-on-tag
  .github/workflows/build-deploy-pudl.yml
  .github/workflows/release.yml
Labels: testing, zenodo, release

#3096 Update CEMS partitions to handle year-quarter files
  docs/release_notes.rst
  src/pudl/etl/__init__.py
  src/pudl/etl/epacems_assets.py
  src/pudl/extract/epacems.py
  src/pudl/metadata/sources.py
  src/pudl/output/epacems.py
  src/pudl/package_data/settings/etl_fast.yml
  src/pudl/package_data/settings/etl_full.yml
  src/pudl/settings.py
  src/pudl/transform/epacems.py
  src/pudl/workspace/datastore.py
  src/pudl/workspace/resource_cache.py
  test/integration/epacems_test.py
  test/unit/settings_test.py
  test/unit/workspace/datastore_test.py
Labels: epacems, new-data

#3128 Table diff tools
  devtools/sqlite-table-diff.ipynb
  src/pudl/helpers.py
  test/unit/helpers_test.py
Labels: testing

#3024 Refactor calculation of annualized_respondents_ferc714
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
  src/pudl/output/ferc714.py
Labels: community

#3155 Update lockfiles on pre-commit
  .github/workflows/update-conda-lockfile.yml
  .pre-commit-config.yaml
Labels: dependencies

#3127 Script to sync a local directory up to a Zenodo DOI
  devtools/zenodo/zenodo_data_release.py
  docker/gcp_pudl_etl.sh
Labels: zenodo, release

#3158 Attempt to create sandbox data release in nightly builds.
  .github/workflows/build-deploy-pudl.yml
  docker/gcp_pudl_etl.sh
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
Labels: zenodo, release

#3159 Merge dev into main for 2023-12-14
  .github/ISSUE_TEMPLATE/annual_updates.md
  .github/ISSUE_TEMPLATE/existing_data_updates.md
  .github/workflows/update-conda-lockfile.yml
  .pre-commit-config.yaml
  devtools/zenodo/zenodo_data_release.py
  docker/gcp_pudl_etl.sh
  docs/dev/existing_data_updates.rst
  docs/dev/index.rst
  docs/dev/pudl_id_mapping.rst
  docs/release_notes.rst
  environments/conda-linux-64.lock.yml
  environments/conda-lock.yml
  environments/conda-osx-64.lock.yml
  environments/conda-osx-arm64.lock.yml
Labels: nightly-builds

#3157 Alter output path for the nightly builds
  .github/workflows/build-deploy-pudl.yml
Labels: nightly-builds

#3160 Add EPA CEMS concurrency limit to `pudl_etl`
  src/pudl/etl/__init__.py
  src/pudl/etl/cli.py
  src/pudl/helpers.py
Labels: dagster, nightly-builds

#3156 Remove obsolete Docker data access instructions.
  README.rst
  docs/data_access.rst
Labels: docs

#3178 Update EPA CEMS docs for quarterly data, new table name.
  docs/data_access.rst
  docs/templates/data_source_parent.rst.jinja
  docs/templates/epacems_child.rst.jinja
  src/pudl/metadata/classes.py
  src/pudl/metadata/sources.py
Labels: epacems, docs

#3164 Improve nightly build and deployment logic
  .github/release.yml
  .github/workflows/build-deploy-pudl.yml
  .github/workflows/docker-build-test.yml
  .github/workflows/release.yml
  docker/Dockerfile
  docker/gcp_pudl_etl.sh
Labels: nightly-builds

#3188 Clean up nightly build/deploy w/o nightly branch update.
  .github/workflows/build-deploy-pudl.yml
  docker/gcp_pudl_etl.sh
Labels: nightly-builds

#3193 Tell setuptools_scm to ignore non-version tags
  pyproject.toml
Labels: release

#3194 Clarify consistency check and lower threshold from 75% to 74%
  src/pudl/analysis/eia_ferc1_record_linkage.py
  src/pudl/analysis/record_linkage/classify_plants_ferc1.py
Labels: ferc1, ccai

#3197 Reduce FERC1 match threshold in test to 85%
  test/integration/record_linkage_test.py
Labels: ferc1, ccai, nightly-builds
