Repository catalyst-cooperative/pudl, pull requests merged in 2023-02, with the labels that each got.

#2200 Retain all reported EIA sector codes for harvesting
  src/pudl/package_data/eia923/column_maps/boiler_fuel.csv
  src/pudl/package_data/eia923/column_maps/generation_fuel.csv
  src/pudl/package_data/eia923/column_maps/generator.csv
  src/pudl/transform/eia923.py
Labels: eia923, eia860, harvest

#2258 Add EIA 176 to sources.py
  src/pudl/metadata/sources.py
Labels: metadata, eia176, inframundo

#2089 Docs updates for Annual Updates
  devtools/ferc1-etl-debug.ipynb
  devtools/ferc1/ferc1-new-year.ipynb
  docs/dev/annual_updates.rst
  docs/dev/dev_setup.rst
  docs/dev/run_the_etl.rst
Labels: inframundo

#2205 Add `electricity_sales_by_rate_schedule_ferc1` table
  docs/release_notes.rst
  src/pudl/extract/ferc1.py
  src/pudl/metadata/fields.py
  src/pudl/metadata/resources/ferc1.py
  src/pudl/package_data/settings/etl_fast.yml
  src/pudl/package_data/settings/etl_full.yml
  src/pudl/transform/ferc1.py
  src/pudl/transform/params/ferc1.py
  test/unit/transform/ferc1_test.py
  test/validate/ferc1_test.py
Labels: rmi

#2276 Rework of FERC to EIA logistic regression model
  setup.py
  src/pudl/analysis/ferc1_eia.py
Labels: inframundo

#2308 Add fuel allocation release notes
  docs/release_notes.rst
Labels: eia923, analysis, docs

#2281 Extract 860 EnviroAssoc and EnviroEquip Tables in PUDL
  src/pudl/package_data/eia860/column_maps/boiler_cooling.csv
  src/pudl/package_data/eia860/column_maps/boiler_info.csv
  src/pudl/package_data/eia860/column_maps/boiler_mercury.csv
  src/pudl/package_data/eia860/column_maps/boiler_nox.csv
  src/pudl/package_data/eia860/column_maps/boiler_pm.csv
  src/pudl/package_data/eia860/column_maps/boiler_so2.csv
  src/pudl/package_data/eia860/column_maps/boiler_stack_flue.csv
  src/pudl/package_data/eia860/column_maps/cooling_equipment.csv
  src/pudl/package_data/eia860/column_maps/emission_control_strategies.csv
  src/pudl/package_data/eia860/column_maps/emissions_control_equipment.csv
  src/pudl/package_data/eia860/column_maps/fgd_equipment.csv
  src/pudl/package_data/eia860/column_maps/fgp_equipment.csv
  src/pudl/package_data/eia860/column_maps/multifuel_existing.csv
  src/pudl/package_data/eia860/column_maps/multifuel_retired.csv
  src/pudl/package_data/eia860/column_maps/stack_flue_equipment.csv
  src/pudl/package_data/eia860/file_map.csv
  src/pudl/package_data/eia860/page_map.csv
  src/pudl/package_data/eia860/skipfooter.csv
  src/pudl/package_data/eia860/skiprows.csv
  src/pudl/transform/eia860.py
Labels: inframundo

#2224 Integrate FERC-EIA record linkage into PUDL
  devtools/environment.yml
  setup.py
  src/pudl/analysis/__init__.py
  src/pudl/analysis/ferc1_eia.py
  src/pudl/analysis/plant_parts_eia.py
  src/pudl/glue/ferc1_eia.py
  src/pudl/output/ferc1.py
  src/pudl/output/pudltabl.py
  src/pudl/package_data/glue/ferc1_eia_null.csv
  src/pudl/package_data/glue/ferc1_eia_train.csv
  test/integration/output_test.py
Labels: glue, eia923, ferc1, eia860, rmi

#2311 Fix google auth error in tox-pytest
  .github/workflows/tox-pytest.yml
  tox.ini
Labels: inframundo

#2309 Convert FERC1 -> EIA missing ID validation ET[L] to Dagster
  src/pudl/extract/ferc1.py
  src/pudl/glue/ferc1_eia.py
  src/pudl/package_data/settings/etl_full.yml
  src/pudl/transform/ferc1.py
  test/conftest.py
  test/integration/glue_test.py
  tox.ini
Labels: dagster, inframundo

#2299 Update integration tests to work with Dagster ETL
  .github/workflows/tox-pytest.yml
  src/pudl/convert/datasette_metadata_to_yml.py
  src/pudl/etl/__init__.py
  src/pudl/extract/ferc1.py
  src/pudl/ferc_to_sqlite/__init__.py
  src/pudl/glue/ferc1_eia.py
  src/pudl/metadata/classes.py
  src/pudl/package_data/settings/etl_full.yml
  src/pudl/transform/ferc1.py
  test/conftest.py
  test/integration/datasette_metadata_test.py
  test/integration/epacems_test.py
  test/integration/etl_test.py
  test/integration/glue_test.py
  tox.ini
Labels: dagster, inframundo

#2300 Convert epacems_to_parquet command to run dagster asset
  src/pudl/convert/epacems_to_parquet.py
  src/pudl/io_managers.py
Labels: dagster, inframundo

#2254 Add spot fix function/class
  docs/release_notes.rst
  src/pudl/transform/classes.py
  src/pudl/transform/ferc1.py
  src/pudl/transform/params/ferc1.py
  test/unit/transform/classes_test.py
  test/validate/ferc1_test.py
Labels: ferc1, data-cleaning, rmi, xbrl

#2312 Update previous balancing_authority_code_eia fixes for plants_eia860
  docs/release_notes.rst
  src/pudl/transform/eia.py
Labels: inframundo

#2322 Breakpoints in Dagster
  devtools/materialize_asset.py
Labels: inframundo

#2316 Update doi to point to new epacamd_eia archive
  docs/release_notes.rst
  src/pudl/glue/epacamd_eia.py
  src/pudl/metadata/resources/glue.py
  src/pudl/workspace/datastore.py
  test/validate/epacamd_eia_test.py
Labels: epacems, rmi

#2324 Fix primary key duplication
  devtools/materialize_asset.py
  src/pudl/io_managers.py
  src/pudl/output/ferc1.py
  test/conftest.py
Labels: inframundo

#2326 Update local cache when using `--gcs-cache-path`
  src/pudl/workspace/datastore.py
Labels: inframundo

#2332 Configure dagster env vars from settings if not set already
  src/pudl/cli.py
  src/pudl/ferc_to_sqlite/cli.py
  src/pudl/helpers.py
  src/pudl/workspace/setup.py
  test/conftest.py
Labels: dagster, inframundo
